---
title: "map_colors_function3"
author: "Andrew Valadez"
date: "April 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's look at the poor old function

This is the function code from Barry's student
```{r}
##Old Function

map.colors <- function (value, high.low, palette) {
  proportion <- ((value-high.low[1]) / (high.low[2]-high.low[1]))
  index <- round ((length (palette) -1) * proportion)+1
  return (palette[index])
}
```


Now let's try to understand this function...

```{r}
map.colors2 <- function (x, 
                         high.low = range(x), 
                         palette = cm.colors(100)) {
  
  #Determine where in the 'high.low' range our values of 'x' lie
  percent <- ((x - high.low[1])/(high.low[2]-high.low[1]))
  
  # Where in the 'palette' vector of colors is the 'percent'
  index <- round((length(palette)-1 )*percent)+1
  
  
  return (palette[index])
}
```

## Working with our own functions

My first fucntion

```{r}
add <- function(x,y=1) {
  #sum the input x and y
  x+y
}
```


Lets test our first function

```{r}
add(5)
```

```{r}
add(1,4)
```





```{r}
add(c(1:5))
```

```{r}
add(c(1:3),30)
```
### if more than 2 inputs
```{r}
#add(1,3,3)
```

```{r}
#add(x=1,y='5')
```



## Resclae functioin

```{r}
rescale <- function(x) {
             rng <-range(x)
             (x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale(1:10)
```

```{r}
rescale( c(1,2,NA,3,10) )
```

```{r}
rescale2 <- function(x) {
             rng <-range(x, na.rm=TRUEre)
             (x - rng[1]) / (rng[2] - rng[1])
}



```

```{r}
#rescale2( c(1,2,NA,3,10) )
```

Want to get an error on this message 
```{r}
#recale( c(1,10,”string”) )
```



```{r}
rescale3 <- function(x, na.rm=TRUE, plot=TRUE) {
 if(na.rm) {
 rng <-range(x, na.rm=na.rm)
 } else {
 rng <-range(x)
 }
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 #
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4) 
 }
 print("I can see it in ...")
 
 return(answer)
}
```





```{r}
rescale3( c(1,2,NA,3,10) )
```

