---
title: "GeneAssignment"
author: "Andrew Valadez"
date: "June 5, 2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Question 7


```{r}
library(bio3d)
```



```{r}
degus <- read.fasta("data/talin1degus.fasta")
homosapian <- read.fasta("data/talin1homosapian.fasta")
mouse <- read.fasta("data/talin1mouse.fasta.txt")
nakedmolerat <- read.fasta("data/talin1nakedmolerat.fasta")
novelrat <- read.fasta("data/talin1novelrat.fasta")
spalax <- read.fasta("data/talin1spalax.fasta")
squirrel <- read.fasta("data/talin1squirrel.fasta.txt")

```

```{r}
combinedfastas <- seqbind(novelrat,homosapian,degus,nakedmolerat,mouse,spalax , squirrel)
```

```{r}
alignedseqs <- seqaln(aln = combinedfastas$ali, exefile = "muscle.exe", outfile = "alignedfile.fa", protein = TRUE)
```

```{r}
try2 <- read.fasta("alignedfile.fa")
```

```{r}
dim(try2$ali)
```

```{r}
try2score <- seqidentity(try2$ali)
```

```{r}
heatmap(try2score)
```

```{r}
colnames(try2score) <- c("Rattus_norvegicus","Mus_Musculus", "Homo_sapiens", "Heterocephalus_glaber", "Nannospalax_galili", "Ictidomys_tridecemlineatus", "Octodon_degus")

#colnames(try2score)

rownames(try2score) <- c("Rattus_norvegicus","Mus_Musculus", "Homo_sapiens", "Heterocephalus_glaber", "Nannospalax_galili", "Ictidomys_tridecemlineatus", "Octodon_degus")
```

```{r}

heatmap(try2score, margins = c(11,11), cexRow = 1, cexCol = 1)
```

```{r}
par("mar")
```



```{r}
consensusseq <- consensus(try2$ali)
```

```{r}
blastedseq <- blast.pdb(consensusseq$seq)
```


```{r}
hits <- plot.blast(blastedseq)
```
```{r}
head(hits$pdb.id)
```

```{r}
annotatedhits <- pdb.annotate(hits$pdb.id)
```

```{r}
##doitforthecombining <- blastedseq$hit.tbl
#combinedhits <- cbind(doitforthecombining,annotatedhits)
```
```{r}
fastathing <- consensusseq$seq

fastathingtest <- as.fasta(fastathing)

aliplz <- fastathingtest$ali
```

