---
title: "20180427_in_class"
author: "Andrew Valadez"
date: "April 27, 2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
# Generate some example data for clustering
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```

```{r}
km <- kmeans(x,centers=2,nstart=20)
km

#nstart says how many times to run
```
30 points per each cluster
bunch of components
```{r}
km$centers
```

```{r}
plot(x, col=km$cluster, pch=16)
points(km$centers, col="blue", pch=11)
```




```{r}
# First we need to calculate point (dis)similarity
# as the Euclidean distance between observations
dist_matrix <- dist(x)
#convert to matrix to see the structure and dimensions
#View(dist_matrix)
#View(as.matrix(dist_matrix))

dim((as.matrix(dist_matrix)))
# The hclust() function returns a hierarchical
# clustering model
hc <- hclust(d = dist_matrix)
# the print method is not so useful here
hc 
```


```{r}
plot(hc)
```


```{r}
plot(hc)
abline(h=6, col='red') # baseically draws where you are slicing it up
grps <- cutree(hc, h=6) # cuts on height 6, or could cut at k groups k=2 for ex

table(grps)
```
```{r}
plot(x,col=grps)
```


Tries didfferent cutting
```{r}
plot(x,col=cutree(hc,k=6))
```

```{r}
plot(hc)
identify(hc)
```

only coordinate that matters is height order does not matter 




```{r}
# Step 1. Generate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```


```{r}
#use dist hclust plot and cutree fx to return 2 and 3 cluster
yourturndist <- dist(x)
dim(x)
#View(as.matrix(yourturndist))
dim(yourturndist)


```


```{r}
tiredturn<- hclust(d=yourturndist)
plot(tiredturn)
```





```{r}
plot(tiredturn)
abline(h=2.5, col='red') # baseically draws where you are slicing it up
grps <- cutree(hc, k=2) # cuts on height 6, or could cut at k groups k=2 for ex

table(grps)
```



```{r}
plot(tiredturn)
abline(h=2, col='red') # baseically draws where you are slicing it up
grps <- cutree(hc, k=3) # cuts on height 6, or could cut at k groups k=2 for ex

table(grps)
```











```{r}
mydata <-  read.csv("expression.csv", row.names = 1)
dim(mydata)
head(mydata)


```


```{r}
#lets do pca
pca <- prcomp(t(mydata), scale = TRUE)

attributes(pca)
```
```{r}
#pca
#not useful print fx
```

```{r}
## A basic PC1 vs PC2 2-D plot
plot(pca$x[,1], pca$x[,2]) 
```

```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100,1)
pca.var.per
```

this was our cliff after pc1 who really cares generally

```{r}
barplot(pca.var.per, main="Scree Plot", xlab="Principal component")
```

```{r}
## A vector of colors for wt and ko samples
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```

```{r}
as.factor(colnames(mydata))
```

we just want to split string to two characters


```{r}
substr( colnames(mydata),1,2)
```
woohoo
now can do as facoor
```{r}
as.factor(substr( colnames(mydata),1,2))
```
so have two levels so can color the wt and ko different
```{r}
mycols <- as.factor(substr( colnames(mydata),1,2))
plot(pca$x[,1], pca$x[,2], col=mycols, pch=10,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)"))

```






#Your turn UK Food


```{r}
x <- read.csv("UK_foods.csv")
dim(x)
```


```{r}
head(x)
```


```{r}
rownames(x) <- x[,1]
x <- x[,-1]
head(x)
```

```{r}
dim(x)
```

```{r}
View(x)
```


```{r}
heatmap(as.matrix(x))
# too laxy to fix the window but the idea is there
```



```{r}
pca <- prcomp( t(x) )
summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
text(pca$x[,1], pca$x[,2], colnames(x))
```

```{r}
#gives percent of variance for each pca
v <- round( pca$sdev^2/sum(pca$sdev^2) * 100 )
v
```

```{r}
# gives the cum proportion;;;;
z <- summary(pca)
z$importance
```

```{r}
barplot(v, xlab="Principal Component", ylab="Percent Variation")
```

```{r}
cumsum(v)
```

